### PR TITLE
SwanHelp in Lab

### LINKED ISSUE #29: Create example of lab extension
To demonstrate how other extensions should be organized.

### PR DESCRIPTION
**Pull request by diocas**
This is SwanHelp as a Lab extension.
Closes #29 #30 

## Model for extension development
I've created this to be used as a model for all other extensions in the repo. The base organization comes from the [Jupyterlab cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts)
I've demoted the nbextension to a subfolder and made the lab extension the main code. But both live in the same place (as they should...).
All extensions can also be distributed using the corresponding Python module. So, after doing `pip install swanhelp`, the lab extension will also be installed and we will be able enable the nbextension. This simplifies the installation process.
While not automatic yet (#38), this code is also ready to be pushed to pypi and npm.

## The help extension in lab
This extension will create a subgroup under "help" with link to the documentation (opened inside an iframe), community and SNow.
I expect to add the Gallery link also in this subgroup, but this will come from the SwanGallery extensio (#34)

### Images
image
image
image

### CODE REVIEW

**Comment by diocas** [comment]
@prasanthkothuri @etejedor Let me know if you approve this organisation model.

**Comment by etejedor** [comment]
Very nice @diocas ! My comments:

- I like the subgroup under "Help", I actually had the same thought in a conversation with Omar today, before seeing your proposal, so :+1: 
- The iframe with the help looks nice, but I guess this means we are not preserving the upper blue bar and the bottom copyright area in the whole interface (otherwise there would be a duplication).

Perhaps it is a good time to start discussing (even if grosso modo) how we would like SWAN to look like in JupyterLab. This would also determine how Omar is going to develop the extension to enable environments in projects (LCG releases, experiment stacks).

**Comment by diocas** [comment]
@etejedor I have a ticket for that: #37 .
I don't believe we were ever going to put the footer. But the header, I would still like to have it. I have also thought for a while about replacing the header with a sidebar.. But at this moment I don't know if it will be easy/possible.

**Comment by diocas** [comment]
@etejedor can we merge this?

**Pull request merged**
